### ISSUE TITLE
Token format changes leading to FormatException errors

### ISSUE THREAD

**Issue by MakotoAme** [Tyrrrz/DiscordChatExporter#828]
### Version

2.33.2

### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Details

This was mentioned in #823 but the author closed the issue themselves.

I can reproduce this on the Windows Discord client at the moment, but the issue is not present on Linux.

There seems to be a change in the token format, but it may only impact some clients or be a part of a change that is slowly rolling out.

I noticed that the token format was weird when attempting to use the client recently. The token is 172 characters in length, and has a format similar to this:
`###########:################################################################################################################################################################`

\# can be any alphanumerical character along with `+` and `/`

The `:` prefix remains consistent even when relogging.

This client does not have multiple accounts associated with it, so I don't think that should be related.

Here is the build information:
```
Stable 123251 (321dd3f) Host 1.0.9004 Windows 10 64-Bit (10.0.22581)
```

### Steps to reproduce

- Attempt to grab and use the token on an affected client.
    - If the client is not affected by this change, it cannot be easily reproduced.

**Comment by Tyrrrz** [comment]
Did you find a way to make it work?

**Comment by MakotoAme** [comment]
> Did you find a way to make it work?

Unfortunately not. I tried splitting the token to just what was after the `:` but that still resulted in a format error, I believe because `/` is considered invalid by the application at the moment. Stripping those characters results in an authentication error, and I can't see any other way to make the tokens format work.

Whether or not the token would work without the format error I can't say, I can try patching the software to force it to accept the tokens and see if it works but I'm not familiar with C# development. If it's not too difficult to compile a version that won't throw a format error I'm happy to test it however!

My solution was just to grab the token from the Linux client, since that still has the traditional token format.

The error also occurs on Windows no matter which Discord account I use. Unless it somehow changes again, I should be able to keep reproducing it locally.

**Comment by Tyrrrz** [comment]
DCE itself does not verify the token, it just sends it to Discord as is.
Try checking the Networks tab in Discord to see which token it sends (as Authentication header).

**Comment by MakotoAme** [comment]
> DCE itself does not verify the token, it just sends it to Discord as is. Try checking the Networks tab in Discord to see which token it sends (as Authentication header).

Ah, the token in the authentication header does work!

And it is completely different from the token in the applications tab. Interesting.

**Comment by Tyrrrz** [comment]
> And it is completely different from the token in the applications tab. Interesting.

That's unusual

**Comment by Tyrrrz** [comment]
Ah, I looked at the error from the linked issue and it appears the exception is thrown by .NET when the header is set. I wonder if some character indeed causes it to break.

**Comment by Tyrrrz** [comment]
Should be fixed in latest CI build

**Comment by GingerDesigne** [comment]
> DCE itself does not verify the token, it just sends it to Discord as is. Try checking the Networks tab in Discord to see which token it sends (as Authentication header).

Can't locate _Authentication header_ for some reason :(

**Comment by GingerDesigne** [comment]
Nothing working for me. I tried every single way but still getting that error :( 
_Error pulling guilds and channels_

**Comment by Tyrrrz** [comment]
> > DCE itself does not verify the token, it just sends it to Discord as is. Try checking the Networks tab in Discord to see which token it sends (as Authentication header).
> 
> Can't locate _Authentication header_ for some reason :(

https://github.com/Tyrrrz/DiscordChatExporter/wiki/Troubleshooting#i-cant-findcopy-my-token

**Comment by GingerDesigne** [comment]
> > > DCE itself does not verify the token, it just sends it to Discord as is. Try checking the Networks tab in Discord to see which token it sends (as Authentication header).
> > 
> > 
> > Can't locate _Authentication header_ for some reason :(
> 
> https://github.com/Tyrrrz/DiscordChatExporter/wiki/Troubleshooting#i-cant-findcopy-my-token

Sorry, but no _Header_ section shows up in my panel :(
![image_2022-04-17_032946356](https://user-images.githubusercontent.com/94997323/163695319-db6689dc-35c0-4a55-a645-70d77d342752.png)

**Comment by Tyrrrz** [comment]
@GingerDesigne 

You have to click on a request first

![image](https://user-images.githubusercontent.com/1935960/163695542-044e483a-b053-444d-8be0-87526d37bad2.png)

**Comment by GingerDesigne** [comment]
> @GingerDesigne
> 
> You have to click on a request first
> 
> ![image](https://user-images.githubusercontent.com/1935960/163695542-044e483a-b053-444d-8be0-87526d37bad2.png)

Still no luck for me :(
![Header 2](https://user-images.githubusercontent.com/94997323/163698470-30d9f51f-c505-43eb-9404-967314370220.PNG)

**Comment by Tyrrrz** [comment]
Click on "Request headers"...

**Comment by GingerDesigne** [comment]
> Click on "Request headers"...

Sorry, nothing happened :((
I tried every single way yet none of them works out.

1- Signed in from Opera browser. No token there, absolutely No. Followed every step you told me to but no success either.
2- Switched from vanilla Discord to Canary one. There Token, but DiscordChatExporter gives the same error every single time:  Error pulling guilds and channels..

This shouldn't be this messy.. I'm really sad :(( I just want to backup my data, nothing more.
![Header 3](https://user-images.githubusercontent.com/94997323/163750583-eb0310c4-bef4-4944-aeeb-a55c54c39a03.PNG)

**Comment by Tyrrrz** [comment]
Uncheck "Font" and check "XHR" instead on the right of the filter box

**Comment by GingerDesigne** [comment]
> Click on "Request headers"...

Thank you dear Tyrrrz! It worked at last. I successfully backed up my data and for that I'm grateful to you. Many thanks

**Comment by GingerDesigne** [comment]
> Uncheck "Font" and check "XHR" instead on the right of the filter box

Thank you dear Tyrrrz! It worked at last. I successfully backed up my data and for that I'm grateful to you. Many thanks :)
